### ISSUE TITLE
circular import

### ISSUE THREAD

**Issue by deltaLuki** [tataratat/napf#10]
In some python environment it is not possible to run test, because of an ImportError. 
`ImportError: cannot import name '_napf' from partially initialized module 'napf' (most likely due to a circular import) `

**Comment by deltaLuki** [comment]
You can see the error in the current [workflow](https://github.com/tataratat/napf/actions/runs/3673866865/jobs/6211409317).

**Comment by j042** [comment]
It seems installing packing with `python3 setup.py install` and calling the tests at repo-root causes this problem. Replacing `install` to `develop`, works for this purpose. Check [here](https://github.com/tataratat/napf/actions/runs/3674301696)

**Comment by deltaLuki** [comment]
For version 0.1.0 I think it should be possible to use the install flag.

**Comment by j042** [comment]
Isn't this just an issue for this specific case? If you install it from PyPI or from wheel, this shouldn't happen.
