### ISSUE TITLE
Question about third_party/nanoflann.hpp [gcc-13 compatibility]

### ISSUE THREAD

**Issue by carlosal1015** [tataratat/napf#21]
Hi, I would like to mention that when I compile `splinepy` in a system with [gcc 13 or later](https://archlinux.org/packages/core/x86_64/gcc), no matter if using standard 11, 14 or 17 shows the [following error](https://github.com/tataratat/napf/files/12388767/log_1.txt). Will be nice [include one header](https://gcc.gnu.org/gcc-13/porting_to.html) for avoid future problems.
[![asciicast](https://asciinema.org/a/603707.svg)](https://asciinema.org/a/603707)
These steps I follow to reproduce the issue.

##### [`start.sh`]()

```bash
#!/usr/bin/env bash

docker build -t test .
docker run -ti --rm test /run.sh  2>&1 | tee -a log.txt
```

##### [`run.sh`]()

```bash
#!/usr/bin/env bash

# [1/6] system-wide upgrade
sudo pacman -Syu --noconfirm
cd
curl -LO https://aur.archlinux.org/cgit/aur.git/snapshot/python-gustaf.tar.gz
tar -xvf python-gustaf.tar.gz
cd python-gustaf
# [2/6] Install dependency python-gustaf
makepkg -si --noconfirm
# [3/6] Show contents and import module only for testing
pacman -Ql python-gustaf
python -c "import gustaf"
# [4/6] Install makedependencies
sudo pacman -S --noconfirm python-build python-installer python-setuptools python-wheel cmake ninja pybind11 git
# [5/6] Pull sources 
git clone https://github.com/tataratat/splinepy.git
cd splinepy
# [6/6] Not use ssh protocol because we do not have installed openssh
sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
git submodule init
git -c protocol.file.allow=always submodule update
python -m build --wheel --skip-dependency-check --no-isolation
```

##### [`Dockerfile`](https://gitlab.com/dune-archiso/images/dune-archiso/-/blob/main/Dockerfile)

```dockerfile
FROM registry.gitlab.com/dune-archiso/images/dune-archiso:latest
COPY ./run.sh /
ENTRYPOINT ["/run.sh"]
```

Also I have some curiosity about
- if possible to add [this feature](https://blog.pypi.org/posts/2023-04-20-introducing-trusted-publishers) instead secrets when publish with twine.
- if user have [nanoflann](https://aur.archlinux.org/packages/nanoflann) 1.5.0 in local machine, could be use [if-else condition in CMakeLists.txt](https://gitlab.dune-project.org/staging/dune-logging/-/blob/master/CMakeLists.txt#L44-L133) in order to do not duplicate files in hard disk.
- one solution for this issue that I found is [here](https://github.com/tataratat/napf/compare/main...carlosal1015:napf:gcc-13-compatibilty) when I use

#### [`run.sh`]()

```bash
#!/usr/bin/env bash

# [1/6] system-wide upgrade
sudo pacman -Syu --noconfirm
cd
curl -LO https://aur.archlinux.org/cgit/aur.git/snapshot/python-gustaf.tar.gz
tar -xvf python-gustaf.tar.gz
cd python-gustaf
# [2/6] Install dependency python-gustaf # nanoflann
makepkg -si --noconfirm
# [3/6] Show contents and import module only for testing
pacman -Ql python-gustaf
python -c "import gustaf"
# [4/6] Install makedependencies
sudo pacman -S --noconfirm python-build python-installer python-setuptools python-wheel cmake ninja pybind11 git
# [5/6] Pull sources 
git clone https://github.com/carlosal1015/splinepy.git
cd splinepy
git switch gcc13-compatibility
# [6/6] Not use ssh protocol because we do not have installed openssh
sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
git submodule init
git -c protocol.file.allow=always submodule update
python -m build --wheel --skip-dependency-check --no-isolation
```
[![asciicast](https://asciinema.org/a/603719.svg)](https://asciinema.org/a/603719)
if some question is affirmative I could try to help.

**Comment by j042** [comment]
Hi @carlosal1015, thanks for the informative issue description!

> * if possible to add [this feature](https://blog.pypi.org/posts/2023-04-20-introducing-trusted-publishers) instead secrets when publish with twine.

good point, I will look into those

> * if user have [nanoflann](https://aur.archlinux.org/packages/nanoflann) 1.5.0 in local machine, could be use [if-else condition in CMakeLists.txt](https://gitlab.dune-project.org/staging/dune-logging/-/blob/master/CMakeLists.txt#L44-L133) in order to do not duplicate files in hard disk.

this as well

> * one solution for this issue that I found is [here](https://github.com/tataratat/napf/compare/main...carlosal1015:napf:gcc-13-compatibilty) when I use

as this is a mere copy of the upstream project, I'd prefer not to make any local changes. Perhaps you could write an issue / create a PR for nanoflann?

**Comment by carlosal1015** [comment]
Many thanks, [I confirm](https://aur.archlinux.org/packages/python-napf) the issue was solved.

**Comment by j042** [comment]
that's awesome, thank you!
